### ISSUE TITLE
Support for template-less PCR amplification

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_backend#105]
Hi @manulera! Correct me if I'm wrong but I have not come across a way to create a way to add a new DNA source from a template-less PCR.

This is something I use, for instance, to synthesize CRISPR repair fragments from two 100-bp oligos with 20 annealing bp in the middle, without the need of a template (see [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5445975/) and [this](https://pubmed.ncbi.nlm.nih.gov/33313420/) for reference). Depending on the specific case, the sequence of these oligos may be the same as the endogenous locus or have some alterations (point mutations, deletions...). Do you think this concrete use-case should be implemented? If yes, I can try to look into it.

**Comment by dgruano** [comment]
This would be somewhat linked to #102

**Comment by manulera** [comment]
Yes, this should definetely be supported. Do you want to have a go at it yourself? I can give you some advice on how to do it.
