### ISSUE TITLE
Add a limit of max. size to the uploaded files

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning_backend#18]

**Comment by erik-whiting** [comment]
hey @manulera, can I take a stab at this issue? If so, do you want the size value to be configurable somewhere or set in a constant in one of the scripts? or did you have a value in mind already?

**Comment by manulera** [comment]
Hey @erik-whiting sure thing! Sorry I was a bit lazy on the issue description, it refers to this function, which is for now the only entry point where the user can upload files.

https://github.com/manulera/ShareYourCloning_backend/blob/d503a685f955f63fa1cc1db87617dda851129cc5/main.py#L41

I would say for now the file-limit can be hard-coded, and maybe 100MB is a good starting point. I doubt someone would try something bigger than that. At some point it can be moved to a config file.

The function should return HTTP 413 Payload Too Large response status code if the user would attempt to submit a big file.

By the way, as it is now the backend and frontend don't actually work together. I have made significant changes to the backend lately, but haven't had the time to adjust the frontend accordingly, so you cannot really get both to work together for now. Hopefully I should fix this by next week, but you know how it goes with working in the free time...

**Comment by erik-whiting** [comment]
@manulera cool, sounds good. The challenge here is that you can't really know a file's size until it's on your server. There's 3 ways to go about fixing this, let me know which approach you like best:
1. Check the file size on the server with `os.path` and reject it if it's too big. The downside here is this doesn't stop the file from actually being uploaded onto your server, so it kind of defeats the purpose.
2. Process the uploaded file in pieces on the server. Once you've processed the allotted size, reject the file and raise an error if there's more to process. The challenge here is dealing with temp files but that's not such a big deal.
3. Reject the file entirely based on the HTTP header `content-length` value. This would essentially stop a file that's too big from ever reaching the server. Technically we could combine this approach with 1 or 2 above too as an extra layer of protection. The challenge here is a) someone can manually overwrite the `content-length` header to something small and send a big file anyway and b) We'd have to resort to middleware for this solution, which is fine, it's just an extra layer of complexity.

Personally I think 2 is the best approach along with some front-end validation when the time comes (i.e., in the JavaScript when someone is uploading a file, you write a function that rejects a file greater than 100mb).
Let me know which approach you like most and I'll get to it, thanks!

**Comment by manulera** [comment]
Hey @erik-whiting thanks for the comprehensive response. Actually, I think front-end validation is probably the most sensible way of doing it for now. I think nobody is going to use API calls in a while, so probably we can deal it with it in the future. I will create an issue in the frontend repo once I make the major changes. Hopefully this weekend I find the time for it.

I will close for now, and open it if the time comes where this is an issue.
