### ISSUE TITLE
Additional sources for plasmids

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_backend#196]
Snapgene stores many plasmids in https://snapgene.com/plasmids. If we decide to support this, the search option can be accessed with the following API https://www.snapgene.com/api/plasmids/search?string=, so the user could search from the SYC frontend and the backend could then import the selected plasmid. The sequence can be accessed from an API, using the information returned by the search API: https://www.snapgene.com/local/fetch.php?set=fluorescent_protein_genes_and_plasmids&plasmid=pEGFP-N1

AddGene has a "digital-only" database of plasmids from other vendors, which is no longer maintained: https://www.addgene.org/vector-database/ Some may be available from the Snapgene database, but otherwise they could be accessed from AddGene (I am sure we have discussed this but I don't find the issue). The sequence can be copied from a text box.

Issue #175 also fits here.

**Comment by manulera** [comment]
Hi @dgruano I completely forgot about this one, but I added support for SnapGene plasmids yesterday anyway on https://github.com/manulera/ShareYourCloning_backend/pull/214. I did not use their search request, but scraped the list instead ( I only saw the search box after). In any case, not sure they will forever allow to make a search request from the outside, so it's not too bad anyway!

**Comment by dgruano** [comment]
Hey! Sounds reasonable to keep an offline copy. I remember you mentioned a repo with side helper scripts for SYC. It might be good to periodically check that our offline database is up to date.

**Comment by manulera** [comment]
The code it's here, and it will be updated once a day: https://github.com/manulera/SnapGene_crawler
