### ISSUE TITLE
Requesting large sequences crashes the backend server

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_backend#201]
I requested the GenBank ID `CU329670.1` and the app got stuck for a bit. Then the server crashed and was unavailable for a second.

As a means of protection, we may want to limit those requests of very large sequences.

Other tests I did were:
- Requesting a very large genome region:
Genome region > Custom coordinates in reference genome > pombe > 1 to 5500000

- Requesting a genome region out of range:
Same, but: 5500000 to 6000000
Returns: `coordinates fall outside the sequence`

-  Requesting a large genome region out of range: 
Same, but 1 to 6000000.
Returns: `coordinates fall outside the sequence` in local, but hangs the server in production

**Comment by manulera** [comment]
This is a very good point, will do this now.
