### ISSUE TITLE
Exclude example files from pre-commit hooks

### ISSUE THREAD

**Issue by dgruano** [manulera/ShareYourCloning_backend#229]
Hi @manulera ! After adding some example plasmid files, the pre-commit hook for the end-of-file line modified them. Do you think we should keep this? Or should we exclude example files?

**Comment by manulera** [comment]
It's good practice to have EOF in all files, so I would say it's good that ape and gb files are also picked up.

Files without an EOF line don't work well when you want to do text manipulation using bash.
