### ISSUE TITLE
Refactor endpoints

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning_backend#238]
They should be refactored into separate files. This will allow for instance to use the pcr endpoint in other more specific endpoints, such as the arabidopsis cloning avoiding circular imports.

**Comment by manulera** [comment]
This is a big one @dgruano, I guess you are not working on anything specific right now, but I am re-organising the code in the repo

**Comment by dgruano** [comment]
Go ahead @manulera, I am still stuck on pydna with the USER implementation, so I haven't touched the SYC side of things yet. Good luck!
