### ISSUE TITLE
Requesting genes

### ISSUE THREAD

**Issue by manulera** [manulera/ShareYourCloning_backend#31]
Hi @kimrutherford

I have been meaning to ask about this for a while. I would like to add a feature to request DNA sequences of genes. Something like the PomBase sequence viewer, where from a unique identifier of a gene, you can request its sequence  + upstream and downstream extra sequence as indicated as well as the sequence features belonging to that gene. The initial request body could look something in these lines:

```javascript
{
  gene_id: 'SPAC1687.10',
  expand_3prime: 1000, // ensembl style
  expand_5prime: 1000, // ensembl style
}
```

I would want the sequence with features associated with the gene_id. For this particular example, the ones that would come from this request with `Parent: SPAC1687.10`:

https://rest.ensembl.org/overlap/region/schizosaccharomyces_pombe/I:919726-922098?feature=gene;feature=transcript;feature=cds;feature=exon;content-type=application/json

And I would want to have the output in genbank / gb format. 

What do you think would be the easiest way to do this? I can see that using ensembl, I could get the coordinates from the gene_id , and then from that separately request the sequence and the features, convert the features to gb features (but that would require some coordinate transformation).

All this to say, is there an API to request sequence + features directly in genbank format from genome coordinates?

**Comment by kimrutherford** [comment]
Hi Manu.

I don't know of an API that does what need.  If you can get the information from Ensembl, you can write a GenBank file using BioPerl or BioPython.  You could also read an EMBL or GenBank file using BioPerl or BioPython to avoid using an API.

**Comment by manulera** [comment]
Hi @kimrutherford thanks for answering!

I see, yes, definetely reading files would be easier, but the idea is to be able to provide only the genomic coordinates and the genome assembly code to document the source of a sequence. I could download a handful of genomes and support only those, but for a first version I think supporting ensembl is probably best, since it has so many genomes.
